pylintrc: disabled pylint reimport warning
[pylint correction]

pylint 0.23.0 warns for what it perceives to be redundant imports. However, the
following is not redundant, but it generates a warning:

    import email
    import email.header

Proof:

    >>> import email
    >>> email.header
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'header'
    >>> import email.header
    >>> email.header
    <module 'email.header' from '/usr/lib/python2.7/email/header.pyc'>

Instead of cluttering up the import sections of python files with comments to
locally disable this warning, I decided to turn it off altogether.